version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  market-price-handler:
    image: market-price-handler:latest
    environment:
      DB_HOST: db
    ports:
    - "8080:8080"
    depends_on:
      - db